### ISSUE TITLE
Preference page cannot be created

### ISSUE THREAD

**Issue by stelfrich** [knime-ip/knip-ilastik#20]
Trying to open the preferences page for the nightly ilastik integration (0.4.1.v201712101850) with KNIME 3.5.2 on macOS 10.12.6 throws the following error:

```
Unable to create the selected preference page.
An error occurred while automatically activating bundle org.knime.knip.ilastik (558).
```

with the following stack trace in the KNIME log:

```
2018-03-05 09:52:21,192 : ERROR : Worker-2 : RepositoryManager :  :  : Node org.knime.knip.ilastik.nodes.headless.IlastikHeadlessNodeFactory' from plugin 'org.knime.knip.ilastik' could not be created: Can't load factory class for node: org.knime.knip.ilastik.nodes.headless.IlastikHeadlessNodeFactory The corresponding plugin bundle could not be activated!
2018-03-05 09:52:21,194 : DEBUG : Worker-2 : RepositoryManager :  :  : Node org.knime.knip.ilastik.nodes.headless.IlastikHeadlessNodeFactory' from plugin 'org.knime.knip.ilastik' could not be created: Can't load factory class for node: org.knime.knip.ilastik.nodes.headless.IlastikHeadlessNodeFactory The corresponding plugin bundle could not be activated!
java.lang.IllegalArgumentException: Can't load factory class for node: org.knime.knip.ilastik.nodes.headless.IlastikHeadlessNodeFactory
	at org.knime.workbench.repository.RepositoryFactory.createNode(RepositoryFactory.java:121)
	at org.knime.workbench.repository.RepositoryManager.readNodes(RepositoryManager.java:352)
	at org.knime.workbench.repository.RepositoryManager.readRepository(RepositoryManager.java:169)
	at org.knime.workbench.repository.RepositoryManager.getRoot(RepositoryManager.java:596)
	at org.knime.workbench.repository.RepositoryManager.getRoot(RepositoryManager.java:609)
	at org.knime.workbench.workflowcoach.ui.WorkflowCoachView$3.run(WorkflowCoachView.java:248)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.core.runtime.CoreException: Plug-in org.knime.knip.ilastik was unable to load class org.knime.knip.ilastik.nodes.headless.IlastikHeadlessNodeFactory.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
	at org.knime.workbench.repository.RepositoryFactory.createNode(RepositoryFactory.java:118)
	... 6 more
Caused by: java.lang.ClassNotFoundException: An error occurred while automatically activating bundle org.knime.knip.ilastik (558).
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:116)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:529)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:325)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:423)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:564)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
	... 10 more
Caused by: org.osgi.framework.BundleException: Exception in org.knime.knip.ilastik.preferences.IlastikPreferencesPlugin.start() of bundle org.knime.knip.ilastik.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:795)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:932)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:470)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:107)
	... 20 more
Caused by: java.lang.IllegalStateException: Selected file is not a valid ilastik executable
	at org.knime.knip.ilastik.preferences.IlastikPreferencesPlugin.initOptionsService(IlastikPreferencesPlugin.java:50)
	at org.knime.knip.ilastik.preferences.IlastikPreferencesPlugin.start(IlastikPreferencesPlugin.java:29)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
	... 27 more
```

**Comment by imagejan** [comment]
I had a similar (I think) error a few days ago when updating. It disappeared when using a new workspace. I'm not sure if these settings are somehow linked to the workspace?

**Comment by stelfrich** [comment]
> It disappeared when using a new workspace. I'm not sure if these settings are somehow linked to the workspace?

Well, that's not really a solution. Plus, I haven't used the integration with that workspace. I guess there is a default path in that field that points to nowhere meaningful on my machine.

**Comment by gab1one** [comment]
I will look into this issue this week, I have changed some things in the Ilastik settings page, that must have caused this.

**Comment by gab1one** [comment]
I moved the experimental changes to a separate branch, the nighlty-ilastik integration should now work like the released one.

**Comment by stelfrich** [comment]
Thanks for looking into this @gab1one! I won't have time to verify until the end of the week but will get back to you on Friday.
