### ISSUE TITLE
ArrayIndexOutOfBoundsException with 3D data

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip-ilastik#7]
I get an `ArrayIndexOutOfBoundsException` from `ImgWriter2` when trying to use the _Ilastik Headless_ node with 3D data.

Here's an example workflow:
[Ilastik Tests.zip](https://github.com/knime-ip/knip-ilastik/files/375384/Ilastik.Tests.zip)

and a very simple Ilastik project that I used (please unzip):
[knip-ilastik-tests.zip](https://github.com/knime-ip/knip-ilastik/files/375386/knip-ilastik-tests.zip)

This is the exception from `knime.log`:

```
java.lang.ArrayIndexOutOfBoundsException: 3
	at net.imglib2.AbstractInterval.dimension(AbstractInterval.java:243)
	at net.imglib2.AbstractWrappedInterval.dimension(AbstractWrappedInterval.java:59)
	at net.imagej.ImgPlus.dimension(ImgPlus.java:220)
	at net.imglib2.AbstractWrappedInterval.dimension(AbstractWrappedInterval.java:59)
	at net.imglib2.AbstractWrappedInterval.dimension(AbstractWrappedInterval.java:59)
	at net.imagej.ImgPlus.dimension(ImgPlus.java:220)
	at org.knime.knip.io.nodes.imgwriter2.ImgWriter2.writeImage(ImgWriter2.java:280)
	at org.knime.knip.io.nodes.imgwriter2.ImgWriter2.writeImage(ImgWriter2.java:231)
	at org.knime.knip.ilastik.nodes.headless.IlastikHeadlessNodeModel.execute(IlastikHeadlessNodeModel.java:241)
	at org.knime.core.node.NodeModel.execute(NodeModel.java:732)
	at org.knime.core.node.NodeModel.executeModel(NodeModel.java:566)
	at org.knime.core.node.Node.invokeFullyNodeModelExecute(Node.java:1146)
	at org.knime.core.node.Node.execute(Node.java:933)
	at org.knime.core.node.workflow.NativeNodeContainer.performExecuteNode(NativeNodeContainer.java:556)
	at org.knime.core.node.exec.LocalNodeExecutionJob.mainExecute(LocalNodeExecutionJob.java:95)
	at org.knime.core.node.workflow.NodeExecutionJob.internalRun(NodeExecutionJob.java:179)
	at org.knime.core.node.workflow.NodeExecutionJob.run(NodeExecutionJob.java:110)
	at org.knime.core.util.ThreadUtils$RunnableWithContextImpl.runWithContext(ThreadUtils.java:328)
	at org.knime.core.util.ThreadUtils$RunnableWithContext.run(ThreadUtils.java:204)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.knime.core.util.ThreadPool$MyFuture.run(ThreadPool.java:123)
	at org.knime.core.util.ThreadPool$Worker.run(ThreadPool.java:246)
```

**Comment by imagejan** [comment]
The version served by the nightly build update site is still serving `0.2.2.v201607220824`. Is this fix already available to end users somewhere?

**Comment by dietzc** [comment]
I will try to cut a nightly build release today.
